title: [My Site Title, will add later]
description: >- 
  [My site description, will add later]
baseurl: "" # If the site is hosted at a subpath (e.g., /blog), set baseurl: "/blog"
url: "https://yuxuan-luo-dev.github.io" # The base URL of your site

theme: jekyll-theme-cayman # You can change this to any GitHub Pages-supported theme

social_links:
  github: https://github.com/tbd
  linkedin: https://linkedin.com/tbd
