title: Yuxuan Luo' homepage
baseurl: "" # If the site is hosted at a subpath (e.g., /blog), set baseurl: "/blog"
url: "https://yuxuan-luo-dev.github.io" # The base URL of your site

remote_theme: "mmistakes/minimal-mistakes@4.24.0" # Use the Minimal Mistakes theme
plugins:
  - jekyll-remote-theme # Required plugin for remote themes
  - jekyll-seo-tag # Optional for better SEO
  - jekyll-sitemap # Optional for generating a sitemap

header_pages:
  - about.md
  - cv.md
  - blog.md
  - projects.md

social_links:
  github: https://github.com/tbd
  linkedin: https://linkedin.com/tbd
